# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfec4439cba29baaa65823485e886d511c3e554b60c865c99153a0b78b7c5e51877440e0403b5ba55b73021deeaf8992a2ba181f31b768f37edd9112ec20d588

test:
  secret_key_base: 45fcebc64345f6d08e6a27a83754aa55c13aa955b17e5e393464ff7cb9ee7db6dff7286f48f6129de74ccdfc30b38fd861b416a94d27972d1b0b8075f51ab65d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>